#Steps Specific Configuration
steps:
  xsDeploy:
    apiUrl: 'https://api.dhlhvie0.eu.airbus.corp:36633'
    docker:
      dockerImage: 'ppiper/xs-cli'
    loginOpts: '--skip-ssl-validation'
    org: 'airbus'
    space: 'DEV'
    mtaPath: 'WebIDEDemo1.mtar'

